### ISSUE TITLE
"No such file": Folder name is being ignored when trying to open tid file

### ISSUE THREAD

**Issue by MaxGyver83** [ProgrammingIncluded/TiddlerToHTML#1]
I've just found this project and tried it. Unfortunately, I get this error:

```
~/repos/TiddlerToHTML (master|…) [1] ▶ python3 tparse.py ~/repos/wiki/Notizen/tiddlers /tmp/html
Traceback (most recent call last):
  File "tparse.py", line 82, in <module>
    main()
  File "tparse.py", line 70, in main
    inroot = tid_tree(f)
  File "tparse.py", line 36, in tid_tree
    with open(filename, "r") as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'Striche in Neo2.tid'
```

The problem is that `tid_tree` tries opening that file without its folder name prepended:

```py
# Create the parse tree for the tiddler
def tid_tree(filename):
    with open(filename, "r") as infile:
```

`filename` is `Striche in Neo2.tid` but it should be `~/repos/wiki/Notizen/tiddlers/Striche in Neo2.tid`.

**Comment by ProgrammingIncluded** [comment]
Hi @MaxGyver83 sorry for the delay in response, it has been a while since I used the scripts. I plan to be deprecating this project since I have found a work around. I recommend instead the following: Go to the tiddler you want to export, go to click the arrow on the tiddler, then `export Tiddler` > `static HTML`. Sincere apologies.
